# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

#Es cuando se dispara una accion especifica, puede ser por un cron, un pull request exitoso etc.
trigger:
- master

variables:
  resourceGroup: 'microservices'
  containerName: 'hello-world-pipeline-2'
  imageName: 'devs4j/hello-world-pipeline-2'
  dnsName: 'hello-world-pipeline-2-141695'

pool:
  vmImage: 'ubuntu-lastest'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: 
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
